services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: itinno
      POSTGRES_DB: itinnodb
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    networks:
      - intern

  rabbitmq:
    image: 'rabbitmq:4.2'
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: itinno
      RABBITMQ_DEFAULT_PASS: itinnom3ssanger
    networks:
      - intern

  backend:
    container_name: "innoeditor-backend"
    image: ghcr.io/hs-esslingen-it-innovationseditor-v2-0/itinno-backend:main
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/itinnodb
      - SPRING_DATASOURCE_USERNAME=itinno
      - SPRING_DATASOURCE_PASSWORD=secret
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}-backend.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}-backend.rule=Host(`${APP_URL}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.${APP_NAME}-backend.middlewares=${APP_NAME}-strip-api"
      - "traefik.http.routers.${APP_NAME}-backend.tls.certresolver=le"
      - "traefik.http.middlewares.${APP_NAME}-strip-api.stripprefix.prefixes=/api"
      - "traefik.http.services.${APP_NAME}-backend.loadbalancer.server.port=8080"
    networks:
      - traefik
      - intern

  frontend:
    container_name: "${APP_NAME:-frontend}"
    image: "ghcr.io/hs-esslingen-it-innovationseditor-v2-0/itinno-frontend:main"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME:-innovationseditor-frontend}.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME:-innovationseditor-frontend}.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.${APP_NAME:-innovationseditor-frontend}.priority=1"
      - "traefik.http.routers.${APP_NAME:-innovationseditor-frontend}.tls.certresolver=le"
      - "traefik.http.services.${APP_NAME:-innovationseditor-frontend}.loadbalancer.server.port=80"
    networks:
    - traefik

  traefik:
    image: traefik:v3.6
    container_name: "traefik"
    restart: unless-stopped
    networks:
      - traefik
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      #Let's Encrypt configuration
      - "--certificatesresolvers.le.acme.email=lescit07@hs-esslingen.de"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"

networks:
  traefik:
    external: true
  intern:
    external: false
